#version: '3'
#networks:
#  laravel:
#services:
#  nginx:
#    image: nginx:stable-alpine
#    container_name: nginx
#    ports:
#      - "8002:80"
#    volumes:
#      - ./src:/var/www/
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php
#      - mysql
#    networks:
#      - laravel
#  mysql:
#    image: mysql:5.7.22
#    container_name: mysql
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: test_docker
#      MYSQL_USER: dunglv
#      MYSQL_PASSWORD: 12345678
#      MYSQL_ROOT_PASSWORD: dunglv
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    networks:
#      - laravel
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: php
#    volumes:
#      - ./src:/var/www
#    ports:
#      - "9000:9000"
#    networks:
#      - laravel
version: '3'
services:
  db:
    image: postgres
    container_name: postgresql
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
  web:
    build: ./docker-file/
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  pgadmin4:
    image: dpage/pgadmin4:3.3
    container_name: pgadmin4
    ports:
      - 8003:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always